### ISSUE TITLE
Armature is imported as empties rather than an actual armature.

### ISSUE THREAD

**Issue by StanleySweet** [nrgsille76/io_scene_max#1]
Hey,

Thanks for the addon! I wanted to use it to port old 0 A.D. meshes from Max to Blender, but unfortunately it seems that armatures and vertex groups are not ported at all and instead the bones show up as empties. Is there anything I can do to help you debug it? Here are two CC-BY-SA 3.0 mesh files.

<img width="1095" alt="Capture d’écran 2024-06-02 à 15 52 13" src="https://github.com/nrgsille76/io_scene_max/assets/6837402/b41e2dcf-9c94-496b-a42b-6e32531c62b6">

[horses.zip](https://github.com/user-attachments/files/15525512/horses.zip)

**Comment by nrgsille76** [comment]
@StanleySweet There was no intention yet to import armatures and vertex groups. Biped objects are imported as empties  to keep the hierarchy tree but bones are not supported yet. The focus of improvement at the moment is importing the correct transformations. There are a lot of differences in 3ds max files depending on the software version, some use psr transformation, others are using tcp, both can be with or without bezier floats. Then some are using Bipslave control or animation keyframes. It is not easy to make all compatible with blender and before we can focus on armatures, the transformation part has to be correct.
