### ISSUE TITLE
The addon doesn't work

### ISSUE THREAD

**Issue by jwvdzw** [nrgsille76/io_scene_max#10]
Hi, Thank you for creating this addon. The problem is that it doesn't do anything.
I've installed the addon via the extensions menu in the preferences. After that i tried a fresh 3ds max file from a few primitive objects with different materials. But when i import this file with the addon nothing happens. Also no error message of reaction in the blender console. When i enable the option to create a collection on importing, the collection is created but still no objects are imported.
I also tried to save the max file as an older version of max. (2021 for example). But that also didn't work..

What is going wrong? Please help, i would like this addon to work!

Thanks
Jan Willem

**Comment by nrgsille76** [comment]
@jwvdzw I tested the addon with about 400 .max files with no problems, sometimes the textures may not be loaded because they are not in the right path. Can you upload the file wich does not work? Otherwise I can not reproduce the error

**Comment by jwvdzw** [comment]
Hi @nrgsille76 , and thanks for the reply. I updated to 1.5.2
I am able to import older max files from our library now with this addon. But the one simple max file i created for testing still doesn't work. It's in the attachment of this comment.
Because the scene contains simple 3d objects that are created as primitives i also tested it with a edit poly on top of it. But that didn't solve it.
[test2.max.zip](https://github.com/user-attachments/files/16390825/test2.max.zip)

**Comment by nrgsille76** [comment]
@jwvdzw  I checked the file, most data is compressed and it seems to be no zip compression (maybe .gz) My script only supports compressed data if it is .zip compressed, there is no support for other compression formats yet.
The directory has shown:
 `'saveconfigdata', 'scene_compressed', 'config_compressed', 'fileassetmetadata3', '\x05summaryinformation', 'classdata_compressed', 'dlldirectory_compressed', 'videopostqueue_compressed', 'classdirectory3_compressed', '\x05documentsummaryinformation', 'scripted_ca_defs_compressed'`
