### ISSUE TITLE
Missing bl_info after install

### ISSUE THREAD

**Issue by swingninja** [nrgsille76/io_scene_max#12]
Getting this error message after install.

Warning: add-on missing 'bl_info', this can cause poor performance!: ' ............\addons\\io_scene_max\\__init__.py'

And just like the error message says, it took forever to launch Blender. Using Blender 4.1 LTS

**Comment by nrgsille76** [comment]
This is the extension version, extensions were introduced in Blender 4.2 LTS and the bl_info has to be removed. For older versions the addon version is needed, you can find it on [my other repository](https://github.com/nrgsille76/blender-io-addons)
