### ISSUE TITLE
Blender doesn't import .max files (Addon not working)

### ISSUE THREAD

**Issue by theLeonardoLima** [nrgsille76/io_scene_max#13]
I tried to import 3DS Max files into Blender, but the .max files are not recognized and no error message appears. What could be the issue? How can I resolve this problem?
![image](https://github.com/user-attachments/assets/76cf75f9-4db2-4e7f-85f3-65c1dd4924b9)
![image](https://github.com/user-attachments/assets/a77be5d4-9806-423e-84f0-9d9bb04ebd98)
![image](https://github.com/user-attachments/assets/d5e31838-7c28-4fe5-bb33-09d055e59b69)

**Comment by theLeonardoLima** [comment]
[Uploading OFFICE_OTHER.zip…]()
this is my .MAX file

**Comment by theLeonardoLima** [comment]
Maybe the problem can be in Max version files (3DS MAX 2023)

**Comment by nrgsille76** [comment]
@theLeonardoLima I checked the file and found out that the scene data is compressed with a non supported format. Only .zip format is supported. You can try to save the file in 3ds max without compression. The 3ds max version is not the issue, I also have checked the newest max version without problems

**Comment by theLeonardoLima** [comment]
Sorry for reopening this topic, but, how do i export decompressed .max files?

**Comment by nrgsille76** [comment]
@theLeonardoLima 
uncheck "Compress on Save" in file preferences
https://help.autodesk.com/view/3DSMAX/2025/ENU/?guid=GUID-1AA91F8A-CA4E-4432-9D54-1301305CB44C
