### ISSUE TITLE
Missing geometry

### ISSUE THREAD

**Issue by mts1010** [nrgsille76/io_scene_max#14]
Hello, thank you for creating this add on. But there is an issue when importing some models, - some geometry is just missing. This model is from Maxtree. As you can see the lower trunk, and branches are missing. The model has a Multi/Sub Object material applied to it with several materials plugged in to it. This happens with a lot of other models too. 

Can you please fix this? 

![tree](https://github.com/user-attachments/assets/1c98392a-08e6-415b-ba85-aa9fcbc7cb78)

**Comment by nrgsille76** [comment]
@mts1010  The geometry is not missing, it just exceeds the maximum clipping distance. You can use the scaling options to make the model smaller or you can raise the maximum clipping distance in the view tab

**Comment by mts1010** [comment]
Hey, I appreciate the fast reply. Since I've been working in max exclusively and never thought I was going to try other software, I deleted all export files (fbx, obj) from my library a while ago. Now I have thousands of max files that need to be imported into Blender directly. 

Back to this model - I'm sure this has nothing to do with clipping. I am atttaching another picture from another perspective, with adjusted clipping, where you can clearly see there is no geometry where the branches are supposed to be. The lower trunk is also missing. 

You can clearly see the orange outline. On the bottom I left Blenders default cube for reference.

![tree](https://github.com/user-attachments/assets/d54230f3-8d44-4642-8a43-c32dccb94e45)

Here is another model from the same collection. Again with the branches missing.

![tree 2](https://github.com/user-attachments/assets/2a96e1fb-6125-41ff-a932-e7d6f8b0b741)

I can send you the files if you'd like to check for yourself. Thanks.

**Comment by nrgsille76** [comment]
@mts1010  Yes I need the file to find the issue, you can upload it in a zip here or send it to nrgsille@googlemail.com

**Comment by mts1010** [comment]
Hey, it seems like only certain max files, that I exported were problematic. But I've found another problem. All max files imported into blender are a 100x times too big and the scale transform doesn't work uniformly, when the fbx file contains multiple objects. Setting the scale factor to 0.01 and applying the matrix (on or off) scales objects differently or misplaces them. So the only way to have a correct scale is to join the objects in blender and scale them manually which is time consuming. Can you look into this? I can send you the file.

I have a suggestion. Can you upgrade this script so that max files can be dragged directly into the viewport? And then an import settings window could pop up. This would make importing much easier and faster. 

Thanks.

**Comment by nrgsille76** [comment]
@mts1010  drag & drop is already supported. The scaling option has to be improved, but I did not found a solution yet

**Comment by mts1010** [comment]
Yeah drag and drop is working. I have no idea why it didn't before. Hopefully you are able to improve scaling. 

Thanks for your hard work. You saved me so many hours.
