### ISSUE TITLE
UV issue

### ISSUE THREAD

**Issue by HappyPhal-CG** [nrgsille76/io_scene_max#15]
Hello. I have an issue with UV when I import maxtree model. 
[https://drive.google.com/drive/folders/10YvVmwFnH-D20I_V8WrdFtZnXQMsuFKN?usp=sharing](url)

**Comment by nrgsille76** [comment]
@HappyPhal-CG  I checked the file, the UVW chunk is represented as it was saved. The points are representing a diagonal with most points on the edges. This does not seem to be correct but that is how it was saved.
