### ISSUE TITLE
blender API

### ISSUE THREAD

**Issue by Kelvin-Link** [nrgsille76/io_scene_max#16]
bpy.ops.import_scene.max()
When importing a max file, I found the method bpy.ops.import_scene.max(). However, when I use this method in Python to import a max file, nothing happens. Could you please tell me if this method is currently usable? Thanks！

**Comment by nrgsille76** [comment]
@Kelvin-Link  The use of the operator works in the latest version. The method is:  `bpy.ops.import_scene.max(filepath="*path*")`
