### ISSUE TITLE
Start at requirement prior to 4.2 version

### ISSUE THREAD

**Issue by andremeireles** [nrgsille76/io_scene_max#2]
Is it possible lower the requirement?
Maybe 3.6?
I know this was meant to work within the extensions ecosystem, but blender 4.2 limits the hardware.
So if it can be installed without the extensions philosophy like add-ons already do but with minimal changes, consider doing so as it would improve the workflow and attract new users.

**Comment by nrgsille76** [comment]
@andremeireles Yea the new EVEE takes more hardware performance. The addon can be used from version 4.0 without problems, for version 3.6 I have to change some material settings for the principled bsdf. I can publish a legacy version in my other repository [here](https://github.com/nrgsille76/blender-io-addons). I will try to publish it in the next few days.

**Comment by nrgsille76** [comment]
@andremeireles  A version for Blender 3.6 can now be found [here](https://github.com/nrgsille76/blender-io-addons)

**Comment by andremeireles** [comment]
@nrgsille76 Thank you very much for make a fix in such a short time.
I found a small bug in the legacy version, but I will register it in the other repository.

**Comment by nrgsille76** [comment]
@andremeireles There was a small bug in the LTS version wich is now fixed with commit ad9fc6629f88360389da10b0323ac5a5e2c4f111
