### ISSUE TITLE
Can you make it work in Blender 3.6 ?

### ISSUE THREAD

**Issue by namhari1909** [nrgsille76/io_scene_max#20]
The addon is amazing, but currently, I see that it only supports Blender 4.2 or later. Could you make it compatible with Blender 3.6?
Have a nice day!

**Comment by nrgsille76** [comment]
@namhari1909 There is already an addon for older Blender versions available in my other repository, you only need the single `.py` file, just have a look here:
[blender_io_addons](https://github.com/nrgsille76/blender-io-addons/tree/main/LTS)
