### ISSUE TITLE
Constant error

### ISSUE THREAD

**Issue by GitJoe99** [nrgsille76/io_scene_max#21]
Hi,

I have a load of 3D Max Files (Espona, Archmodels, ZygotePlatinumModels etc.).
They are all at least 40 Years old. I still can load them with 3D Max but always get an error when I try it with the importer in Blender (4.30).

I send you the error Message, maybe you see whats wrong.

Kind Regards

Peter
![Screenshot 2024-12-04](https://github.com/user-attachments/assets/adc45483-2fbb-4cab-acb9-05afa172fc39)

**Comment by nrgsille76** [comment]
@GitJoe99 This error should be fixed in the latest version. Have you updated yet? Otherwise you can upload the zipped `.max` file so I can check it.
Here link to latest version:
https://extensions.blender.org/add-ons/io-scene-max/versions/
