### ISSUE TITLE
No UV Map

### ISSUE THREAD

**Issue by EdmisP** [nrgsille76/io_scene_max#6]
using importer, mesh has no UV Map or Materials

**Comment by nrgsille76** [comment]
To solve this problem I would need to have a look on the .max file. Usually the UV map should import, but if the script raises an exception, the material part will be skipped.

**Comment by EdmisP** [comment]
For test i used MaxTree free sample files:
https://maxtree.org/products/plant-models-vol-60/ for example  MT_PM_V60_Acer_buergerianum_01_01.max

Also tried renderpeople (loads UV, but not material) and Humano (creates grey material but no UV's) sample files

**Comment by nrgsille76** [comment]
@EdmisP  The issues should now be fixed with commit  5ecfc66f39205c8a1956f21b9550f91b3c1bb3c4
