### ISSUE TITLE
.max imports in blender ?

### ISSUE THREAD

**Issue by 0kkyn** [nrgsille76/io_scene_max#8]
Yeah, such a great idea for sure, been working on 3ds for... ok let's not mention this, and currently migrating almost everything at work from first to blender, i do make an heavy use of .fbx imports. 
So i guess this addon might appear as some kind of very big interest for me, and surely (or maybe ?) does it works for small objects... 
but not at all when working on larger scene, even smallest ones :

Scaling misunderstanding (when you do use the function in import parameters) some parts scaled, half the other or somewhat not, 
loads of elements not even imported, not a single texture... well sorry, maybe is this more something like a alpha ?
(sorry being so harsh, and pardon my poor english)
Anyway thanks a lot for the principle, surely will try again in a few... months ?

**Comment by nrgsille76** [comment]
@0kkyn The textures will not load if they are not in the folder or a subfolder of your .max file.
For the other issus I need the file to reproduce the error. The scaling only applies to root objects, all childs should take that into account if they are parented correctly
